### ISSUE TITLE
Change 'toggle' method name to 'toggleVisibility'

### ISSUE THREAD

**Issue by Apisov** [kirtan403/K4Kotlin#2]
I think it's not really clear what method 'toggle' means. Without reading the documentation :)
So my choice is to add a little bit of functionality description to the name of the method.

**Comment by kirtan-inexture** [comment]
Yes, I think that will be good. Thanks for your suggestion. Will do it in the next version.

**Comment by kirtan403** [comment]
Done. Added `toggleVisibility` for `toggle` in commit c255dc2 . Will be released in next update.
`toggle` now marked as deprecated.

**Comment by kirtan403** [comment]
Released in `0.2.0`
